### ISSUE TITLE
[질문]

### ISSUE THREAD

**Issue by seohyun79** [kyohoonsim/KUSF_SPORTS_DATA_ANALYST#2]
이런 에러가 났는데 어느부분이 잘못된건지 잘 모르겠습니다.

문제 : 2018정규시즌에 3루타를 가장 많이 친 타자 3명은?

sqlite> SELECT playerID, 3B FROM Batting WHERE yearID = 2018 ORDER 3B DESC LIMIT 3;
Error: unrecognized token: "3B"

**Comment by seohyun79** [comment]
해결했습니다 ! (숫자로 시작 -> 3B가 아니라 "3B")

**Comment by kyohoonsim** [comment]
잘하셨습니다~!
