### ISSUE TITLE
[질문] 어떻게 해결해야할지 모르겠습니다!

### ISSUE THREAD

**Issue by leejinkyoung** [kyohoonsim/KUSF_SPORTS_DATA_ANALYST#4]
추신수 선수의 타율구하는 것을 복습하고있었는데 
error: no such column: no such 'choosh01' 이라고 계속 뜨는데 어떻게 해결해야할까요?

**Comment by leejinkyoung** [comment]
해결했습니다!

**Comment by kyohoonsim** [comment]
ㅎㅎ 잘하셨습니다
