### ISSUE TITLE
타율 계산해보기

### ISSUE THREAD

**Issue by snoopy994** [kyohoonsim/KUSF_SPORTS_DATA_ANALYST#5]
SELECT playerID, CAST(H AS REAL)/AB AS AVG FROM batting WHERE yearID = **** and playerID = ‘******’;

타율 계산을 위해 위와 같은 식에 연도와 playerID 를 넣었을 때 결과값이 나오지 않고 다시
sqlite>
이 뜨는 경우가 꽤 많습니다! 
왜 그런건가요?

**Comment by kyohoonsim** [comment]
없는 연도와 플레이어아이디를 넣고 조회를 하시면 아무 결과도 나오지 않습니다^^ 참고로 저희가 지금 사용하고 있는 레먼데이터베이스에는 2019년까지의 데이터를 담고 있습니다!
