### ISSUE TITLE
어디서 오류가 뜨는지 모르겠습니다

### ISSUE THREAD

**Issue by dongglami20** [kyohoonsim/KUSF_SPORTS_DATA_ANALYST#6]
![스크린샷(81)](https://user-images.githubusercontent.com/93537559/141146503-ccdee700-0720-421b-aefd-01c38e1f3871.png)

**Comment by kyohoonsim** [comment]
지금 보시면 SELECT 다음에 불필요한 콤마(,) 가 들어가 있네요 ㅎㅎ 이거 지우고 한번 해보세요~!

**Comment by dongglami20** [comment]
수정했습니다! ''')에 오류가 뜬다고 나오는데 지웠다 다시 써도 똑같은 오류가 나옵니다.  문장이 잘못된 걸까요??
![스크린샷(82)](https://user-images.githubusercontent.com/93537559/141329832-95fd60d6-2197-4d5f-91b7-eeaa0f317bd0.png)

**Comment by kyohoonsim** [comment]
wOBA 구하는 식에서 분모에 CAST 함수를 사용했는데 AS REAL이 없네요^^; 그 부분 한번 수정해보세요~!
