### ISSUE TITLE
CH는 투수의 무슨 볼의 약자인가요?

### ISSUE THREAD

**Issue by snoopy994** [kyohoonsim/KUSF_SPORTS_DATA_ANALYST#7]
검색을 해보니 "주심"의 약자라는 글만 보여서 여쭙니다!

**Comment by kyohoonsim** [comment]
CH는 체인지업의 약어입니다.^^

참고로 FF는 패스트볼(직구), SL은 슬라이더, CU는 커브, SP는 스플리터입니다.
